package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"sort"
	"strings"
)

const (
	inputPath  = "./data/stopwords.json"
	outputPath = "./stopwords_gen.go"
)

// This program generates a Go source file containing a merged stop-word map.
func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "genstopwords: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	data, err := os.ReadFile(inputPath)
	if err != nil {
		return fmt.Errorf("read %s: %w", inputPath, err)
	}

	var byLanguage map[string][]string
	if err := json.Unmarshal(data, &byLanguage); err != nil {
		return fmt.Errorf("parse %s: %w", inputPath, err)
	}

	stopWords := make(map[string]struct{})

	for _, words := range byLanguage {
		for _, word := range words {
			word = strings.TrimSpace(strings.ToLower(word))
			if word == "" {
				continue
			}

			stopWords[word] = struct{}{}
		}
	}

	words := make([]string, 0, len(stopWords))
	for word := range stopWords {
		words = append(words, word)
	}
	sort.Strings(words)

	src, err := generateSource(words)
	if err != nil {
		return err
	}

	if err := os.WriteFile(outputPath, src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outputPath, err)
	}

	fmt.Printf("generated %s with %d stop words\n", outputPath, len(words))
	return nil
}

func generateSource(words []string) ([]byte, error) {
	var b strings.Builder

	b.WriteString("// Code generated by internal/textutils/cmd/genstopwords; DO NOT EDIT.\n")
	b.WriteString("// Source: data/stopwords.json\n\n")

	b.WriteString("package textutils\n\n")

	b.WriteString("var stopWords = map[string]struct{}{\n")
	for _, word := range words {
		fmt.Fprintf(&b, "\t%q: {},\n", word)
	}
	b.WriteString("}\n\n")

	b.WriteString(`func IsStopWord(word string) bool {
	_, ok := stopWords[word]
	return ok
}
`)

	out, err := format.Source([]byte(b.String()))
	if err != nil {
		return nil, fmt.Errorf("format generated source: %w", err)
	}

	return out, nil
}
